name: CYTLasso
version: ${project.version}
main: dev.demeng.cytlasso.CYTLasso
depend: [Vault]
author: Demeng
description: A golden lasso plugin.
website: https://demeng.dev/
api-version: 1.13

commands:
  cytlasso:
    description: Main command of CYTLassso.
    aliases: [goldenlasso]